### ISSUE TITLE
AdVideo example needed

### ISSUE THREAD

**Issue by aaronblondeau** [facebook/facebook-nodejs-business-sdk#25]
I am trying to figure out how to build a creative that uses a video.  However, there aren't any docs or examples that show how to accomplish this.  I tried the following based on a working AdImage function that I have 

```
async function createAdVideo(accountId, filepath) {
  const AdAccount = adsSdk.AdAccount;
  const account = new AdAccount(accountId);
  const AdVideo = adsSdk.AdVideo;
  
  var video = await account
  .createAdVideo(
    [],
    {
      [AdVideo.Fields.filepath]: filepath
    }
  )
  
  return video
}
```

But all I ever get is "FacebookRequestError: Video Upload Time Out: Your video upload timed out before it could be completed. This is probably because of a slow network connection or because the video you're trying to upload is too large. Please try again."

**Comment by tjacoel** [comment]
Personally, I ended up doing the request myself for the video upload:
```
const upload_url = `https://graph-video.facebook.com/v2.11/${account.id}/advideos`;

const data = new FormData();
data.append('access_token', FACEBOOK_TOKEN);
data.append('title', video.name);
data.append('file', video);

return axios.post(upload_url, data, {
    headers: {
        'Content-Type': 'multipart/form-data'
    }
}).then(response => {
    return new AdVideo(response.data.id);
});
```

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by spicy-sauce** [comment]
Hi there, 
I'm trying to upload a video using the advideos endpoint as suggested previously here but keep getting 400 - bad request with:
Unsupported post request. Object with ID 'act_************' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api 

Is there any permission needed for using this endpoint? Couldn't find any in the documentation.
Also, can you provide any example that demonstrates how to use the createAdVideo function (this was requested in this thread before - seems like the current implementation does not send the data in multipart, is that right or am I missing something?)

Thanks in advance.
