### ISSUE TITLE
Nodejs Documentation

### ISSUE THREAD

**Issue by imZEH** [facebook/facebook-nodejs-business-sdk#33]
Hello, I would like to ask why nodejs documentation and example doesn't indicate on this link
https://developers.facebook.com/docs/marketing-api/audiences-api
does facebook documentation not yet updated for a long time ?

Thank you

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. Feel free to check out the latest version of the documentation and, if you find aspects missing, please create a new issue or comment here with further details.
