### ISSUE TITLE
Cursor resets http request params

### ISSUE THREAD

**Issue by JoakimLandberg** [facebook/facebook-nodejs-business-sdk#75]
When iterating through a response result set using the Cursor class, the http parameters used for the initial api request gets reset. Most parameters are preserved through the pagination links but if you use security controls such as appsecret_proof (that are not returned in pagination links), you will not be able to fetch the rest of the results using the cursor since any ```cursor.next()``` call will fail with ```API calls from the server require an appsecret_proof argument``` error.

**Comment by michaelwclark** [comment]
I'm pretty sure Iv'e identified the issue. I'm working on a reproduction and will have a PR for the resolution in the next day or so.

**Comment by michaelwclark** [comment]
PR #82 should resolve this. In the meantime you can use my more active forked version 

`npm i @denimlabs/facebook-nodejs-business-sdk`
https://github.com/denimlabs/facebook-nodejs-business-sdk

note that in our version the appsecret_proof is injected at init of the API rather than on the params as was previously the case.

v3.2.0 should include the fix you were looking for. I haven't heavily tested, but did some light testing on it and seems to work.

**Comment by michaelwclark** [comment]
I've updated the PR for this #104 should now resolve this. It's also already implimented in [our fork](https://github.com/denimlabs/facebook-nodejs-business-sdk/). Feel free to `npm i @denimlabs/facebook-nodejs-business-sdk`
