### ISSUE TITLE
How to get 'X-App-Usage' header from response?

### ISSUE THREAD

**Issue by alexescobedo** [facebook/facebook-nodejs-business-sdk#87]
I am currently trying to create a scheduled job to fetch insights, create and update ad accounts, campaigns, etc. I need to constantly check the 'X-App-Usage' header in order to make sure Facebook doesn't limit me.

How can I check this header when using this sdk or do i need the api request object directly?

**Comment by mvhirsch** [comment]
I do need it too. Any solutions so far?

**Comment by markusenglund** [comment]
The sdk doesn't pass on the headers from requests it makes to the library user unfortunately. I ended up having to make changes in the package's code to get them. It was fairly easy to append the headers as a `headers` property on the cursor/array that this package's methods return.

Is this something that we might want to add to the package itself? I could make a PR for it.

**Comment by wgormley** [comment]
yes, i think this should be added to the package itself

**Comment by paceaux** [comment]
I'm currently dealing with this issue; we've built an azure function that runs this report; it's all automated. But I need to throttle the Azure function from making too many requests if we're getting rejections due to x-app-usage. 

It would be great if we could either access that header or have that information put as a property on the response.

**Comment by actuallymentor** [comment]
> Is this something that we might want to add to the package itself? I could make a PR for it.

Being able to detect rate limits reems rather essential, both for `X-Business-Use-Case-Usage` and `x-app-usage`.

@jingping2015 / @vicdus look like the most active contributors, could either of you indicate whether @markusenglund's PR would be welcome?

Ps. @markusenglund if you need help let me know.

**Comment by jingping2015** [comment]
PR are welcome. Let me know if we have one and I am happy to review it.

**Comment by paceaux** [comment]
@jingping2015 The solution we ended up writing was... somewhat complex. We created some custom error types and some recursive retrying functions:

1. When we got an error, we grabbed the url from the error response and hit it again. 
2. We read the header from that response, determined the kind of throttle error we got
3. We also determined how long we had to wait before trying again, and added a few more minutes
4. Then we use recursion to keep requesting the data until it finally comes down. 


I'd be tempted to try a pull request, but I don't know if you all would be fans of this b/c essentially we made it persistent, rather than failing once.

**Comment by jlubeck** [comment]
Can we get this open again?? It's pretty essential to be able to get the header without having to rely on an exception. You get an exception once you've reached the limit, which is already bad. We need to know when we are about to reach it so we stop before that and don't get penalized
